apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project.uuid }}
  labels:
    {{- include "dev-session-template.labels" . | nindent 4 }}
    project.id: {{ .Values.project.id | quote }}
    user.id: {{ .Values.user.id | quote }}
