apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-session-service.fullname" . }}
  namespace: dev-session-service
  labels:
    {{- include "dev-session-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | b64enc | quote }}
